### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rich-junwang** [akoksal/LongForm#2]
Hi, thanks for sharing the great work. One quick question, would you mind adding a license to the repo so that people can use it? Open license like `MIT` would be great. Also I was wondering if the preprocessing scripts would be shared or not. Thanks again.

**Comment by akoksal** [comment]
Sorry for the late reply. We are bound by the restrictions from OpenAI (for the instruction generation part) and the license of language models (OPT, LLaMA, and T5). Apart from their limitations, we provide open license to our models and datasets. We also updated readme according to that.

We plan to release our preprocessing scripts after cleaning it. But we mostly use two scripts: one for training with DeepSpeed and one for generating instructions by calling OpenAI APIs. Thank you for your interest :)

**Comment by rich-junwang** [comment]
Thank you for the help!
